import CancelledError from './CancelledError';
import clearFetch from './clearFetch';
import combineLoadingStates from './combineLoadingStates';
import createDataServiceMiddleware from './createDataServiceMiddleware';
import createHttpService from './createHttpService';
import dataServiceReducer from './dataServiceReducer';
import DeferredPromise from './DeferredPromise';
import defineFetch from './defineFetch';
import getFetch from './getFetch';
import isError from './isError';
import isLoading from './isLoading';
import isNormal from './isNormal';
import isUnknown from './isUnknown';
import ReduxProvider from './ReduxProvider';
import shallowEqual from './shallowEqual';
import useClearFetch from './useClearFetch';
import useDispatch from './useDispatch';
import useFetch from './useFetch';
import ERROR from './ERROR';
import NORMAL from './NORMAL';
import LOADING from './LOADING';
import UNKNOWN from './UNKNOWN';

declare const Resift: {
  CancelledError: typeof CancelledError;
  clearFetch: typeof clearFetch;
  combineLoadingStates: typeof combineLoadingStates;
  createDataServiceMiddleware: typeof createDataServiceMiddleware;
  createHttpService: typeof createHttpService;
  dataServiceReducer: typeof dataServiceReducer;
  DeferredPromise: typeof DeferredPromise;
  defineFetch: typeof defineFetch;
  getFetch: typeof getFetch;
  isError: typeof isError;
  isLoading: typeof isLoading;
  isNormal: typeof isNormal;
  isUnknown: typeof isUnknown;
  ReduxProvider: typeof ReduxProvider;
  shallowEqual: typeof shallowEqual;
  useClearFetch: typeof useClearFetch;
  useDispatch: typeof useDispatch;
  useFetch: typeof useFetch;
  ERROR: typeof ERROR;
  NORMAL: typeof NORMAL;
  LOADING: typeof LOADING;
  UNKNOWN: typeof UNKNOWN;
};

export default Resift;
