import CanceledError from './CanceledError';
import clearFetch from './clearFetch';
import combineStatuses from './combineStatuses';
import createActionType from './createActionType';
import createContextFetch from './createContextFetch';
import createDataService from './createDataService';
import createHttpProxy from './createHttpProxy';
import createShareKey from './createShareKey';
import createStoreKey from './createStoreKey';
import createHttpService from './createHttpService';
import dataServiceReducer from './dataServiceReducer';
import DeferredPromise from './DeferredPromise';
import defineFetch from './defineFetch';
import getFetch from './getFetch';
import isError from './isError';
import isLoading from './isLoading';
import isNormal from './isNormal';
import isUnknown from './isUnknown';
import ResiftProvider from './ResiftProvider';
import shallowEqual from './shallowEqual';
import useClearFetch from './useClearFetch';
import useDispatch from './useDispatch';
import useFetch from './useFetch';
import ERROR from './ERROR';
import NORMAL from './NORMAL';
import LOADING from './LOADING';
import UNKNOWN from './UNKNOWN';

declare const Resift: {
  CanceledError: typeof CanceledError;
  clearFetch: typeof clearFetch;
  combineStatuses: typeof combineStatuses;
  createActionType: typeof createActionType;
  createContextFetch: typeof createContextFetch;
  createDataService: typeof createDataService;
  createHttpProxy: typeof createHttpProxy;
  createShareKey: typeof createShareKey;
  createStoreKey: typeof createStoreKey;
  createHttpService: typeof createHttpService;
  dataServiceReducer: typeof dataServiceReducer;
  DeferredPromise: typeof DeferredPromise;
  defineFetch: typeof defineFetch;
  getFetch: typeof getFetch;
  isError: typeof isError;
  isLoading: typeof isLoading;
  isNormal: typeof isNormal;
  isUnknown: typeof isUnknown;
  ResiftProvider: typeof ResiftProvider;
  shallowEqual: typeof shallowEqual;
  useClearFetch: typeof useClearFetch;
  useDispatch: typeof useDispatch;
  useFetch: typeof useFetch;
  ERROR: typeof ERROR;
  NORMAL: typeof NORMAL;
  LOADING: typeof LOADING;
  UNKNOWN: typeof UNKNOWN;
};

export default Resift;
